site_name: nation.fun Docs
site_url: https://govinda777.github.io/nation.fun/
repo_url: https://github.com/govinda777/nation.fun
docs_dir: docs

theme:
  name: material

nav:
  - 'Início': 'index.md'
  - 'Introdução':
    - 'O que é um Agente?': 'introduction/what-is-an-agent.md'
  - 'Guias':
    - 'Instalação e Primeiros Passos': 'guides/getting-started.md'
  - 'Referência Técnica':
    - 'Integração com WhatsApp': 'reference/whatsapp-integration.md'
  - 'Web3':
    - 'Introdução': 'web3/index.md'
    - 'Carteiras Inteligentes e Custódia': 'web3/erc4337-e-custodia.md'
    - 'Criação de Agentes e NFTs': 'web3/como-criar-agente.md'
    - 'Como Funcinam as Taxas': 'web3/como-as-taxas-sao-cobradas.md'
    - 'Restrições e Limites': 'web3/restricoes-e-limites.md'
    - 'O Smart Contract de Taxas': 'web3/smart-contract-de-taxas.md'
    - 'Transferindo Seus Ativos': 'web3/como-transferir-seus-ativos.md'
