site_name: nation.fun Docs
theme:
  name: material

nav:
  - 'Início': 'index.md'
  - 'Introdução':
    - 'O que é um Agente?': 'introduction/what-is-an-agent.md'
  - 'Guias':
    - 'Instalação e Primeiros Passos': 'guides/getting-started.md'
  - 'Referência Técnica':
    - 'Integração com WhatsApp': 'reference/whatsapp-integration.md'
