name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Run Build, Tests and Generate Report
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Create report directory
        run: mkdir -p reports

      - name: Run BDD tests
        # Use the test:e2e script to ensure server is built and running
        run: npm run test:e2e
        env:
          # Provide dummy values for environment variables required by the tests
          TOKEN_NATION: ${{ secrets.TOKEN_NATION_DUMMY }}
          NEXT_PUBLIC_IS_TESTING: true # To connect to a local Hardhat node if needed

      - name: Generate HTML report
        # Only generate report on push events to the main branch after tests succeed
        run: npm run generate-report

      - name: Upload Test Report artifact
        # Only upload artifact on push events to the main branch
        uses: actions/upload-artifact@v4
        with:
          name: test-report # Name of the artifact
          path: ./reports
